### ISSUE TITLE
webui says wrong username and/or password

### ISSUE THREAD

**Issue by jukito** [barcus/bareos#24]
On a new installation over Docker Swarm, webui says "Sorry, can not authenticate. Wrong username and/or password."

The logs of apache2 says:
`[Wed Jan 16 15:47:43.809829 2019] [:error] [pid 378] [client 10.255.0.2:43224] admin, referer: http://192.20.223.55/

[Wed Jan 16 15:47:43.809915 2019] [:error] [pid 378] [client 10.255.0.2:43224] console_name: admin, referer: http://192.20.223.55/

[Wed Jan 16 15:47:43.813330 2019] [:error] [pid 378] [client 10.255.0.2:43224] PHP Notice:  fwrite(): send of 26 bytes failed with errno=104 Connection reset by peer in /usr/share/bareos-webui/vendor/Bareos/library/Bareos/BSock/BareosBSock.php on line 211, referer: http://192.20.223.55/`

192.20.223.55 it's the ip to acces to webui. On another docker work without problem, but all containers over the same host.

**Comment by jukito** [comment]
Maybe relevant information:
https://bugs.bareos.org/mantis/view.php?id=1033

**Comment by jukito** [comment]
Resolved on the 18.2.5 release.

**Comment by c0r3dump3d** [comment]
Sorry, but I have installed a bareos 18.2.5 in a Centos 7.6 fresh install and the problem persists:

![captura de pantalla de 2019-02-13 10-16-56](https://user-images.githubusercontent.com/5602401/52700618-b02f9480-2f78-11e9-9f12-eb973c1f851a.png)

In the httpd error_log:

`Wed Feb 13 10:11:25.052952 2019] [:error] [pid 8844] [client 10.141.1.90:10702] PHP Notice:  fwrite(): send of 26 bytes failed with errno=104 Connection reset by peer in /usr/share/bareos-webui/vendor/Bareos/library/Bareos/BSock/BareosBSock.php
on line 219,`

**Comment by jukito** [comment]
In the bugtracker of Bareos says the bug it's already fixed in the release.
https://bugs.bareos.org/view.php?id=1033

But @barcus hasn't updated yet :( and we need the webui for the users review. And we haven't any news about any future upgrade by Barcus. Sadly, tomorrow I will start the migration to standalone RedHat 7. I prefer the Docker version but... bad luck.

Sadly, I haven't yet skills to make my own version of Docker/Bareos and the Barcus version it's really good one.

**Comment by jukito** [comment]
> Sorry, but I have installed a bareos 18.2.5 in a Centos 7.6 fresh install and the problem persists:
> 
> ![captura de pantalla de 2019-02-13 10-16-56](https://user-images.githubusercontent.com/5602401/52700618-b02f9480-2f78-11e9-9f12-eb973c1f851a.png)
> 
> In the httpd error_log:
> 
> `Wed Feb 13 10:11:25.052952 2019] [:error] [pid 8844] [client 10.141.1.90:10702] PHP Notice: fwrite(): send of 26 bytes failed with errno=104 Connection reset by peer in /usr/share/bareos-webui/vendor/Bareos/library/Bareos/BSock/BareosBSock.php on line 219,`
> 
> Sorry, I have seen that it's a docker version ...

A note about NOT Docker installation....
->
console {
  Name = admin
  Password = ******
  Profile = webui-admin
  TLS Enable = No
}

Put the line of TLS Enable = no and voilá!

On my new complete installation works with that.

**Comment by c0r3dump3d** [comment]
Nice!!! It's working!!! thank you very much !!!

**Comment by barcus** [comment]
images were updated

docker exec -t -i build_bareos-dir_1 bconsole
Connecting to Director localhost:9101
 Encryption: PSK-AES256-CBC-SHA
1000 OK: bareos-dir Version: 18.2.5 (30 January 2019)

**Comment by Schroeffu** [comment]
> > Sorry, but I have installed a bareos 18.2.5 in a Centos 7.6 fresh install and the problem persists:
> > ![captura de pantalla de 2019-02-13 10-16-56](https://user-images.githubusercontent.com/5602401/52700618-b02f9480-2f78-11e9-9f12-eb973c1f851a.png)
> > In the httpd error_log:
> > `Wed Feb 13 10:11:25.052952 2019] [:error] [pid 8844] [client 10.141.1.90:10702] PHP Notice: fwrite(): send of 26 bytes failed with errno=104 Connection reset by peer in /usr/share/bareos-webui/vendor/Bareos/library/Bareos/BSock/BareosBSock.php on line 219,`
> > Sorry, I have seen that it's a docker version ...
> 
> A note about NOT Docker installation....
> ->
> console {
> Name = admin
> Password = ******
> Profile = webui-admin
> TLS Enable = No
> }
> 
> Put the line of TLS Enable = no and voilá!
> 
> On my new complete installation works with that.

Thank you  so much! After upgrading from 17 to 18.2.5 i couldn't login to the WebUI too. Adding `TLS Enable = No` was helping me too.

I am going to upgrade all the configs this days for best TLS Encryption for sure, but because bareos-dir is also directly on localhost (same host as webui), so far i didn't care about TLS.
